# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Отдел')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(max_length=150, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True)),
                ('mobile_phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('work_phone', models.CharField(blank=True, max_length=10, verbose_name='Внутренний телефон')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user_profile.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
