# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=256, verbose_name='Должность'),
        ),
    ]
