# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='media/', verbose_name='Ваше фото'),
        ),
    ]
