# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('url', models.CharField(help_text='blog:index', max_length=256, verbose_name='Django-URL')),
                ('position', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name_plural': 'Пункт меню',
                'verbose_name': 'Пункты меню',
                'ordering': ['position', 'name'],
            },
        ),
    ]
